### ISSUE TITLE
Búsqueda de assets para entorno

### ISSUE THREAD

**Issue by almasso** [UCM-FDI-DISIA/Damn#11]
Búsqueda o creación de assets para el entorno.
Las texturas deberían ser, preferiblemente, low-poly; y los sonidos, estilo retro y en 16 bits, como se estipula en el GDD.
Deberíamos tener texturas para el suelo, paredes, techo y las coberturas.
Se necesitaría una canción de fondo de las escenas.

- [x] Modelo
- [x] Texturas

**Comment by DavidRainder** [comment]
Finalmente nos hemos decantado por creación propia de los assets. Han sido generados en paint/photoshop y puestos en materiales como textura en blender
