### ISSUE TITLE
Creación de nivel 1

### ISSUE THREAD

**Issue by almasso** [UCM-FDI-DISIA/Damn#12]
Creación del nivel 1 en Blender utilizando los #11  y su posterior exportación utilizando tanto Blender2Ogre para las meshes como nuestro script de parseo para Lua.

**Comment by DavidRainder** [comment]
Generado un archivo "DamnGame.blend" que representa el nivel 1 del juego. Además, se han arreglado algunos problemas del parser de elementos de blender para que funcione mejor.
