### ISSUE TITLE
Búsqueda assets enemigos

### ISSUE THREAD

**Issue by almasso** [UCM-FDI-DISIA/Damn#9]
Búsqueda o creación de assets para los enemigos.
Las texturas deberían ser, preferiblemente, low-poly; y los sonidos, estilo retro y en 16 bits, como se estipula en el GDD.
Se necesitaría un sonido de disparar, de ser herido, uno de morir y un idle.

- [x] Modelo
- [x] Texturas

**Comment by DavidRainder** [comment]
Se ha modelado un demonio en blender y se han hecho las texturas
